export const ENV = {
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXP: process.env.ACCESS_TOKEN_EXP,
  ACCESS_TOKEN_REMEMBER_EXP: process.env.ACCESS_TOKEN_REMEMBER_EXP,
  DISCORD_CLIENT_ID: process.env.DISCORD_CLIENT_ID,
  DISCORD_CLIENT_SECRET: process.env.DISCORD_CLIENT_SECRET,
  DISCORD_REDIRECT_URI: process.env.DISCORD_REDIRECT_URI,
};
